Add a projector observable to CirqDevice
PennyLaneAI/pennylane-cirq pull request #62
Opened 2021-05-27 06:27 UTC by wongwsvincent

Context:
Adding a projector observable to CirqDevice.

Description of the Change:
Implementing projector observable with Cirq's own ```cirq.ProductState.projector```.

Related GitHub PR:
Resolves PR [#1356](https://github.com/PennyLaneAI/pennylane/pull/1356)

2021-05-28 14:43 UTC, josh146 requested changes
Thanks @wongwsvincent! Before I can approve, would you be able to add a small test for the projector observable, to make sure that it works correctly? Since it will be using `Cirq` directly to compute the expectation, rather than using the logic you added to `QubitDevice` (I believe).

I think there are two options here:

- Add a small unit test using the device methods directly
- Write an integration test using a QNode (this would require modifying the `requirements.txt` file so that the latest master of PennyLane is installed instead, e.g.

  ```python
  git+https://github.com/PennyLaneAI/pennylane.git
  ```

Thank you for adding this!

2021-05-28 14:43 UTC, josh146 commented on CHANGELOG.md
> +* Added Projector observable to CirqDevice.
```suggestion
* Added support for the new `qml.Projector` observable in
  PennyLane v0.16 to the Cirq devices.
```

(Just adding a little more details for readers)

2021-05-31 23:15 UTC, wongwsvincent commented
@josh146,  I have only added a ```test_projector_expectation``` function in ```tests/test_expval.py``` as a start, as I have trouble setting up ```qsimcirq``` on my Mac, so I can't run ```make test``` locally and I'm hesitating a bit about whether I should continue committing tests I haven't checked myself locally.

P.S. It would be great if there's any suggestion on how to install ```qsimcirq``` on Mac OS, but I understand this is not an installation related to PennyLane library.

2021-06-01 05:27 UTC, josh146 commented
Thanks @wongwsvincent!

> as I have trouble setting up qsimcirq on my Mac, so I can't run make test locally and I'm hesitating a bit about whether I should continue committing tests I haven't checked myself locally.

This is perfectly fine 🙂 If you want to run the test suite locally, you can explicitly ignore the `qsim` tests, either by only running the test file you have modified,

```
pytest tests/test_expval.py -x --tb=short
```

or by using pytest's [test selector command line argument](https://docs.pytest.org/en/6.2.x/usage.html#specifying-tests-selecting-tests):

```
pytest tests -x --tb=short -k "not (test_qsim or test_qsimh)"
```

> P.S. It would be great if there's any suggestion on how to install qsimcirq on Mac OS, but I understand this is not an installation related to PennyLane library.

Unfortunately I am not sure - I know that `qsim` is quite tricky to install, even on linux! `qsim` _might_ provide a dockerfile to use it with Docker, but apart from that, I am unsure. Note that it is perfectly fine to not run the test locally, and instead rely on CI within the PR :)

2021-06-02 08:18 UTC, wongwsvincent commented
Awesome! Thanks @josh146 , something like ```pytest tests/test_expval.py -x --tb=short``` is exactly what I need. 
I ran that command and it passed the tests successfully. The same tests as the ones I added in ```pennylane/devices/tests/test_measurements.py``` are now included in ```pennylane-cirq/tests/test_expval.py```, ```pennylane-cirq/tests/test_sample.py``` and ```pennylane-cirq/tests/test_var.py```.
Hopefully all the tests on CI will be fine, and the PR will be ready to merge.

2021-06-02 11:36 UTC, josh146 approved these changes
Thanks @wongwsvincent for the extra push with the tests!

The integration tests are still failing, but this is not the fault of your PR, rather, it looks like another bug in the Cirq plugin has been uncovered. Since that is out of scope here, I may override that failing CI check.

2021-06-02 11:36 UTC, josh146 commented on .github/workflows/tests.yml
> +        python-version: [3.7, 3.8]
I removed 3.6, since PL no longer supports it!

2021-06-02 11:36 UTC, josh146 commented on requirements.txt
> +git+https://github.com/PennyLaneAI/pennylane.git
I also updated this to point to PL master, since `qml.Projector` is not present in the stable v0.15 release

2021-06-03 19:33 UTC, wongwsvincent commented
Thanks @josh146 for fixing some of the test errors! 
There are six remaining errors all complaining about the use of ```numpy.complex64``` vs ```complex128```, but they don't look like they are caused by this PR as you have pointed out. 
Please let me know if there's anything I am missing or I can help with this PR.

2021-06-04 05:52 UTC, josh146 commented
> There are six remaining errors all complaining about the use of numpy.complex64 vs complex128, but they don't look like they are caused by this PR as you have pointed out. Please let me know if there's anything I am missing or I can help with this PR.

Yep, they are orthogonal :) I will merge this PR now @wongwsvincent, which allows us to fix these bugs in a separate PR. I have to admit, off the top of my head I'm unsure what the bug is, it will require some investigation.

2021-06-04 05:52 UTC, merged